jobs:

- job: WindowsTest
  pool:
    vmImage: vs2017-win2016
  steps:
  - powershell: ./build.ps1 -Target Test

- job: LinuxTest
  pool:
    vmImage: ubuntu-16.04
  steps:
  - script: ./build.sh

- job: Delivery
  dependsOn:
  - WindowsTest
  - LinuxTest
  pool:
    vmImage: vs2017-win2016
  steps:
    - powershell:  '"Text" | Set-Content Output.txt'
    - powershell: 'cp Output.txt $env:ArifactStagingDirectory'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: Binaries
      